#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/my.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ >> /var/run/my_script.pid

trap 'echo I hate the kill command; rm -f /var/run/my_script.pid; exit 1' SIGTERM
trap 'rm -f /var/run/my_script.pid; exit 1' SIGQUIT
trap "echo Y U no love me?!" SIGINT

while true;
	do
    echo "To infinity and beyond"
    sleep 2;
done;
