#!/usr/bin/env bash
# display numbers from 1 to 20

a=1

while [ $a -le 20 ]; do
	case $a in
	4)
		echo -e "$a\nbad luck from China"
		;;
	9)
		echo -e "$a\nbad luck from Japan"
		;;
	17)
		echo -e "ai\nbad luck from Italy"
		;;
	*)
		echo "$a"
		;;
	esac
	((a+=1))
done
