#!/usr/bin/env bash
# gives info about the "school" file

file="school"
if [ -e "$file name" ]; then
	echo "school file exists"
	if [ -s "$file name" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$file name" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
